### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by adrian-stein** [markguinn/silverstripe-shop-ajax#1]
I am just trying to get this to work with the shop and reading over the read me in this and in silverstripe-shop-ajax I am a little confused as to how to AJAX the cart features. Are you able to provide any assistance.

**Comment by markguinn** [comment]
You should be able just add the "ajax" class (or data-target="ajax" if you prefer that syntax) to any links or forms you want to use ajax. By default if you're using the SideCart template that region will get updated transparently and automatically, provided the template has a single root tag with an id. If you run into any trouble find me on https://gitter.im/burnbright/silverstripe-shop and I'll be happy to help you further.

**Comment by adrian-stein** [comment]
Thanks, I have it working for products with variations but not products without. Looking at the code the hooks for AJAX integration is on the VariationForm.php but not the main AddProductForm.php. Am i missing something or has this been overlooked?

Also it was not working originally and the cart was not updating. I had to go into base.js and change the line $foundRegion.empty().append($region.html()); and remove the .html() before it worked. I am using jQuery version 1.11.3 I am wondering if this version of jQuery is not supported or they have changed methods??

**Comment by markguinn** [comment]
It's possible that was overlooked. This is a relatively new module so the integration points are basically being built out as someone builds a site that needs them. If you submit a PR for a new integration I'll fast-track it.

It's possible there's been a change in jquery though I think I've used the module with 1.11 before. More likely you're just using it in a slightly different way that's uncovered a bug. If you run /ajax/tests/index.html in a browser an the tests pass with you change why don't you submit that back to the ajax module as a PR as well?

Thanks!

**Comment by adrian-stein** [comment]
Ok I have made the PR for it. It is my first time making one and submitting code to a public repo so if I can do anything better or different please let me know as im sure il have more updates to the shop and its module over the next few months!

**Comment by markguinn** [comment]
Great. Can we close this issue out then?
