### ISSUE TITLE
Why does ShoppingCartAjax use cart or form for messages?

### ISSUE THREAD

**Issue by bummzack** [markguinn/silverstripe-shop-ajax#18]
When showing status-messages via AJAX, the `ShoppingCartAjax` extension seems to switch between using `form` or `cart` to get the message.

The most common case:

``` php
if (self::config()->show_ajax_messages && $this->owner->cart) {
    $response->triggerEvent('statusmessage', array(
        'content'   => $this->owner->cart->getMessage(),
        'type'      => $this->owner->cart->getMessageType(),
    ));
    $this->owner->cart->clearMessage();
}
```

…but there's also:

``` php
if (self::config()->show_ajax_messages) {
    $response->triggerEvent('statusmessage', array(
        'content'   => $form->Message(),
        'type'      => $form->MessageType(),
    ));
    $form->clearMessage();
}
```

The extension is added to `AddProductForm` and `VariationForm` where `cart` isn't available. This causes `AddProductForm` to not emit any status messages.

Both `form` and `cart` might be null, so maybe there should be a check of either of them exists and then pull the status message from there?

**Comment by markguinn** [comment]
I think that makes sense to check both.
