### ISSUE TITLE
AJAX Update Cart

### ISSUE THREAD

**Issue by adrian-stein** [markguinn/silverstripe-shop-ajax#4]
I am also trying to allow updating of the cart on the cart page to happen via AJAX.

There does not appear to be an extend option in the __construct method. in CartForn.php I added one in but it does nothing. I also noticed there is already one in CartPage_Controller alike this extend('updateCartForm', $form, $cart); but this method doesn't seem to extend and add the ajax class to it either. Any thoughts??

**Comment by markguinn** [comment]
The site that I built this module for (https://www.apluswhs.com) did not use the CartForm. It just had links for each project to add / remove even on the cart and checkout pages.

It does look like you could do a really similar thing with CartForm that you did with AddProductForm - just add the same type of extension point at the bottom of the updatecart method and then add the ShoppingCartAjax extension in shop-ajax.

**Comment by adrian-stein** [comment]
I saw your site and the cart itself is not AJAX, where as I need mine to be.

I tried adding the extension point at the bottom of the __construct class so I can add the AJAX class but it didn't work, the class was not added. 

Also another issue is that if I add data-ajax-region="Cart" to the table tag in the cart.ss include so the region can be appended by your pushRegion method it creates 2 table tags. We need the template that creates the CartForm be different to the one that gets the replaced after the AJAX submits. Not sure if that makes sense or not?

**Comment by markguinn** [comment]
I don't have time to look into this in depth but I'll try to get to it later. Make sure that your region template (Cart.ss in this case) has one tag at it's root and that the tag has a consistent id. The data-ajax-region bit should be on that root tag if present too.

**Comment by adrian-stein** [comment]
Think I have cracked it. Is there any reason you extend the dataRecord of the Cart Controller and not the controller itself. see line 97 on https://github.com/burnbright/silverstripe-shop/blob/develop/code/cart/CartPage.php

**Comment by markguinn** [comment]
Interesting. This is something we've come across before and different developers have different opinions. I agree with your assessment though and would like to shift the convention for this Shop (see https://github.com/burnbright/silverstripe-shop/pull/349). I just fixed this in the shop develop branch (https://github.com/burnbright/silverstripe-shop/commit/e04eb1f5498d90630b7282b11d2e68507341ea1a)

**Comment by adrian-stein** [comment]
Sounds good to me. Is there any sort of time frames or processes in place for releasing new versions?

**Comment by markguinn** [comment]
We're hoping to release 1.2 by the end of the year and 2.0 along with SilverStripe 4.0 (possibly mid 2016). I generally try for at least releasing once a quarter.
